name: hook_exit_code_fail
description: A package with a build hook that exits with a non-zero code.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  hooks:
    path: ../../../hooks
