abstract class Prompts {
  // To Do: Add few-shot examples for better translation quality.
  static String _fewShotExamples() => '';

  static String translatePrompt(String sourceCode, String bindingsSummary) =>
      '''
convert this code to equivalent Dart code assuming that Dart has the same corresponding classes, methods and fields as the given code programming language generated by JNIGen tool.

Notes:
- when there is a string passed to a parameter it should be converted using ".toJString()" ... while when returned it should be converted using ".toDartString()"
- the nested classes should be resolved by concatenating them using the "_" sign.
- when translate anonymous class implementation to dart it should be converted to be
  "ClassName.implement(\$ClassName(\nmethod1: (param1) {// implementation}))"

here is the generated classes, fields and methods using JNIgen. use them to choose the correct naming for the Dart classes, fields and methods:
```$bindingsSummary```

here is the code that should be converted:
```$sourceCode```

${_fewShotExamples()}
''';
}
