name: corrupt_output_json_build
description: A package with a build hook that writes a syntactically invalid output.json.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  hooks:
    path: ../../../hooks
