name: hook_compilation_fail
description: A package with a build hook that has Dart syntax errors.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  hooks:
    path: ../../../hooks
